disabled_rules:
    - identifier_name
    - trailing_whitespace
    - cyclomatic_complexity
    - multiple_closures_with_trailing_closure
    - unused_closure_parameter
    - type_name
    - comment_spacing

excluded:
  - Pods
  
type_body_length:
  warning: 500
  error: 800

function_body_length:
  warning: 100
  error: 200
  
line_length:
  warning: 500
  error: 800
  
file_length:
  warning: 500
  error: 800

ignores_function_declarations: true
ignores_comments: true
ignores_urls: true
