# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Budi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Budi
pod 'SwiftLint'
pod 'Moya/Combine', '~> 15.0'
pod 'Kingfisher', '~> 7.0'
pod 'naveridlogin-sdk-ios'
pod 'CombineCocoa'

# Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'

# For Analytics without IDFA collection capability, use this pod instead
# pod ‘Firebase/AnalyticsWithoutAdIdSupport’

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Messaging'
pod 'FirebaseFirestore', '~> 8.10.0'
end
